spring.application.name=expenseIncomeManagerBack

# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
# Puerto en el que se levantará tu backend (el 8080 es el de por defecto)
server.port=9393

# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (MYSQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/expense_manager_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ===============================
# 'update' hace que Spring Boot cree o actualice las tablas automáticamente según tus clases Java
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola las consultas SQL que Spring hace por debajo (muy útil para depurar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONFIGURACIÓN DE SUBIDA DE ARCHIVOS
# ===============================
# Aumentamos el límite de tamaño de archivo (por defecto es 1MB)
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Configuración de Email (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ascasovicentemario@gmail.com
spring.mail.password=xcqq kbuf hwjr kdbl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true