spring.application.name=expenseIncomeManagerBack

# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
# Puerto en el que se levantará tu backend (el 8080 es el de por defecto)
server.port=9393

# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (MYSQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/expense_manager_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ===============================
# 'update' hace que Spring Boot cree o actualice las tablas automáticamente según tus clases Java
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola las consultas SQL que Spring hace por debajo (muy útil para depurar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true